### ISSUE TITLE
Update libp2p-crypto dependency

### ISSUE THREAD

**Issue by vyzo** [libp2p/go-libp2p-peer#11]
Can we pull in the newly published libp2p-crypto (with ecc keys)?

version 1.1.0 is QmVC4w2mj5S5SoRH4dk91PjLvdaaKJDJ1aBFnXVLCKNL6C

**Comment by vyzo** [comment]
this also needs to be propagated to go-libp2p as well, so that the shiny new keys are usable!

**Comment by whyrusleeping** [comment]
Yeap! gonna try and get this done when i get back home on wednesday. The internet in china makes the whole dependency updating game _really_ slow. Unless @Kubuxu wants to beat me to this and get it done.

**Comment by vyzo** [comment]
:8ball:

**Comment by Kubuxu** [comment]
go-libp2p-crypto is dependency of a lot of packages (9 to be exact).
It might be wroth waiting until @lgierth finishes tolling for package updates.

**Comment by parkan** [comment]
Hi guys, poking my head in here again 😄 

We're now ready to ship v1 of our concat node, just blocked by this.

**Comment by whyrusleeping** [comment]
@parkan this has been merged in this package, i'm in the process of updating all the packages in the go-libp2p tree today. I'll ping back here once thats made it through

**Comment by parkan** [comment]
@whyrusleeping would also be happy to discuss a more robust way to handle these dependencies w/o waiting for upsteam (or bugging you guys)

**Comment by whyrusleeping** [comment]
@parkan @vyzo I've got them updated up into go-libp2p, and have a PR up against go-ipfs. It took a while because i also took the time to extract out a few more libs from go-libp2p. We're getting very close to having it nicely modularized.

As far as not having to bug us, we're working on making the whole dependency infrastructure much easier to work with. Right now its a bit weird because so much is still in the core go-libp2p package. Once we have that broken up it should get easier to update deps through the tree, and doing something like `gx update --with-deps github.com/libp2p/go-libp2p` would update that package throughout the tree.

**Comment by parkan** [comment]
Fantastic, thank you! Can close this issue now 😄

**Comment by vyzo** [comment]
Thanks guys, we can haz shiny ECC keys!

We've integrated and use them for statement signing -- but retain the RSA keys for peer ids in order to interop with js. 
Any ideas on when js-libp2p-crypto will include them?

**Comment by whyrusleeping** [comment]
Not sure on that end, lets ask @diasdavid and @dignifiedquire

**Comment by daviddias** [comment]
We can add ECC quickly, in fact, the first peer-id's in JS were ECC, we then refactored to be RSA so that it would match go-ipfs.

However, just to make sure, what is the 'statement signing'? Is it something that happens in the app using IPFS? If so, does that mean that you are looking just to have the ECC crypto primitives through libp2p-crypto?

**Comment by vyzo** [comment]
Well, it's an application specific concept, where each node in our network has a publisher id and uses it to sign metadata statements.

We wanted to use the same ECC keys both for the peer ids and the publisher ids, but we also have a js interop requirement (we have a thin node implementation in js). 
So we ended up using two keys -- an RSA key for peer id and an ECC key for publisher id.

We would like to eventually have ECC key support in js-libp2p as well , so that js nodes can also sign statements (and unify the two ids to get rid of the bulky RSA keys :)

**Comment by dignifiedquire** [comment]
@diasdavid what libraries were you using for ecc keys? webcrypto does not support them currently and it would be a pretty big step backwards to start using pure js crypto again.

**Comment by parkan** [comment]
@dignifiedquire it looks like webcrypto does support ecc to me, is there a specific piece that's missing?
