### ISSUE TITLE
problems with inlining ID

### ISSUE THREAD

**Issue by zippy** [libp2p/go-libp2p-peer#32]
Hi folks,

Commit e41f12f that adds inlining breaks my app which expects IDFromPublicKey to always return a sha2-256 hash.  Is there a reason why this new "feature" isn't a parameter, or setable in some way by the client?

Thanks.

**Comment by jvsteiner** [comment]
Out of curiosity, how do you know if those 32 bytes are, in fact, a sha256 hash? do you mean you have logic where you check the ID is what you expect by hashing the public key yourself?

**Comment by Stebalien** [comment]
> Is there a reason why this new "feature" isn't a parameter, or setable in some way by the client?

Yes. For any given key, the peer ID should always be the same. Our motivation for adding ed25519 keys was to support inlining keys however, given that this was optional, we couldn't reliably use it. So, to fix that, we made it mandatory (iff the key is <= 42 bytes in length).

We made this change *now* because we figured we'd have to make it sometime and wanted to minimize the fallout.
